[package]
name = "icicle-bn254"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icicle-core = { path = "../icicle-core" }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
cmake = "0.1"

# [workspace]
